import { Signika_Negative, Rubik } from 'next/font/google';
import './styles/globals.css';

const signikaNegative = Signika_Negative({
  variable: '--font-signika-negative',
  subsets: ['latin']
});
const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin']
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${signikaNegative.variable} ${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
