import { Signika_Negative, Rubik } from 'next/font/google';
import Footer from './components/main/Footer';
import Header from './components/main/Header';
import './styles/globals.css';

const signikaNegative = Signika_Negative({
  variable: '--font-signika-negative',
  subsets: ['latin']
});
const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin']
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${signikaNegative.variable} ${rubik.variable} antialiased`}
      >
        <article className="flex flex-col justify-between min-h-screen">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </article>
      </body>
    </html>
  );
}
